import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{BrowserRouter,useNavigate,useLocation,useParams}from'react-router-dom';import axios from'axios';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';const ORIGIN=API.replace(/\/api\/?$/,'');const api=axios.create({baseURL:API,withCredentials:true});
async function csrf(){return(await api.get('/csrf')).data.csrf}async function mutate(method,url,data){const c=await csrf();return api({method,url,data,headers:{'x-csrf-token':c}})}
function Login({onLogin}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState('');async function go(e){e.preventDefault();setErr('');try{const r=await api.post('/auth/login',{email,password});onLogin(r.data.user)}catch(e){setErr(e.response?.data?.error||'Login failed')}}return <div className="login"><div className="login-card"><div className="leaf">🌿</div><h1>Sundergarh CMS</h1><p>Forest & Wildlife Division · Government of Odisha</p><form onSubmit={go}><input placeholder="Administrator email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="12"/>{err&&<div className="error">{err}</div>}<button>Secure Sign In</button></form></div></div>}
const items=[['Dashboard','dashboard'],['Pages','pages'],['News','news'],['Media Library','media'],['Videos','videos'],['Publications','publications'],['Officers','officers'],['Ranges','ranges'],['Audit Log','audit']];
function App(){const[user,setUser]=useState(null),[tab,setTab]=useState('dashboard');useEffect(()=>{api.get('/auth/me').then(r=>setUser(r.data.user)).catch(()=>{})},[]);if(!user)return <Login onLogin={setUser}/>;return <div className="app"><aside><div className="brand">🌿 <span>Sundergarh<br/><small>Forest CMS</small></span></div>{items.map(x=><button className={tab===x[1]?'active':''} onClick={()=>setTab(x[1])} key={x[1]}>{x[0]}</button>)}<button className="public" onClick={()=>window.open(`${window.location.origin}/site/home`,'_blank')}>View Public Site ↗</button><button className="logout" onClick={async()=>{await mutate('post','/auth/logout',{});setUser(null)}}>Sign Out</button></aside><main><header><div><span className="eyebrow">ADMINISTRATION</span><h2>{items.find(x=>x[1]===tab)?.[0]}</h2></div><div className="user">{user.name}<small>{user.role.replaceAll('_',' ')}</small></div></header><Content tab={tab}/></main></div>}
function Content({tab}){if(tab==='dashboard')return <Dashboard/>;if(tab==='pages')return <PageManager/>;if(tab==='media')return <CrudManager type="media" title="Media Library" fields={[]}/>;if(tab==='news')return <CrudManager type="news" title="News" fields={['title','slug','summary','publishDate','status','featuredImageId']}/>;if(tab==='videos')return <CrudManager type="videos" title="Videos" fields={['title','description','youtubeUrl','category','status','thumbnailMediaId']}/>;if(tab==='publications')return <CrudManager type="publications" title="Publications" fields={['title','description','category','publishDate','status','documentMediaId','coverMediaId']}/>;if(tab==='officers')return <CrudManager type="officers" title="Officers" fields={['name','designation','office','mobile','officePhone','email','sortOrder','status','photoMediaId']}/>;if(tab==='ranges')return <CrudManager type="ranges" title="Ranges" fields={['name','officerName','mobile','phone','email','description','sortOrder','status','photoMediaId']}/>;return <Audit/>}
function Dashboard(){const[data,setData]=useState(null);useEffect(()=>{api.get('/admin/stats').then(r=>setData(r.data))},[]);return <section className="cards">{['pages','news','media','videos','publications','officers','ranges'].map(k=><div className="stat" key={k}><small>{k}</small><strong>{data?.[k]??'—'}</strong><span>Database records</span></div>)}<div className="welcome"><h3>Public content is now database-backed</h3><p>Edit a published page from Pages and open the public site to see the change. Existing portal HTML has been imported as editable page content.</p><button onClick={()=>window.open('/site/home','_blank')}>Open Public Website ↗</button></div></section>}
function PageManager(){const[data,setData]=useState([]),[edit,setEdit]=useState(null),[newPage,setNewPage]=useState(false);const load=()=>api.get('/admin/pages').then(r=>setData(r.data));useEffect(load,[]);return <div className="panel"><div className="toolbar"><div><h3>Public Pages</h3><p>Existing public portal pages are imported and editable here.</p></div><button onClick={()=>setNewPage(true)}>+ New Page</button></div><table><thead><tr><th>Page</th><th>Slug</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{data.map(p=><tr key={p.id}><td><b>{p.title}</b></td><td>{p.slug}</td><td><span className={'badge '+p.status.toLowerCase()}>{p.status}</span></td><td>{new Date(p.updatedAt).toLocaleString()}</td><td><button className="small" onClick={()=>setEdit(p)}>Edit</button> <button className="small" onClick={()=>window.open(`/site/${p.slug}`,'_blank')}>View</button></td></tr>)}</tbody></table>{edit&&<PageEdit page={edit} close={()=>{setEdit(null);load()}}/>}{newPage&&<PageEdit page={{slug:'new-page',title:'New Page',menuLabel:'New Page',metaDescription:'',heroImage:'',bodyHtml:'<main id="main-content"><section class="container"><h1>New Page</h1><p>Start editing this page.</p></section></main>',status:'DRAFT',sortOrder:data.length}} create close={()=>{setNewPage(false);load()}}/>}</div>}
function PageEdit({page,close,create}){const[p,setP]=useState({...page});const save=async()=>{try{if(create)await mutate('post','/admin/pages',p);else await mutate('put','/admin/pages/'+p.id,p);close()}catch(e){alert(e.response?.data?.error||'Save failed')}};return <div className="modal"><div className="modal-card wide"><h3>{create?'Create Page':'Edit: '+page.title}</h3><div className="form-grid"><label>Title<input value={p.title} onChange={e=>setP({...p,title:e.target.value})}/></label><label>Menu Label<input value={p.menuLabel} onChange={e=>setP({...p,menuLabel:e.target.value})}/></label>{create&&<label>Slug<input value={p.slug} onChange={e=>setP({...p,slug:e.target.value})}/></label>}<label>Status<select value={p.status} onChange={e=>setP({...p,status:e.target.value})}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label></div><label>Meta Description<input value={p.metaDescription||''} onChange={e=>setP({...p,metaDescription:e.target.value})}/></label><label>Hero Image URL<input value={p.heroImage||''} onChange={e=>setP({...p,heroImage:e.target.value})}/></label><label>Public Page HTML<textarea rows="22" value={p.bodyHtml} onChange={e=>setP({...p,bodyHtml:e.target.value})}/></label><div className="actions"><button onClick={save}>Save</button><button className="ghost" onClick={close}>Cancel</button></div></div></div>}
function CrudManager({type,title,fields}){const[data,setData]=useState([]),[edit,setEdit]=useState(null);const load=()=>api.get('/admin/'+type).then(r=>setData(r.data));useEffect(load,[type]);const empty=useMemo(()=>Object.fromEntries(fields.map(f=>[f,f==='status'?'DRAFT':f==='sortOrder'?0:''])),[fields]);async function remove(id){if(!confirm('Delete this record?'))return;await mutate('delete','/admin/'+type+'/'+id);load()}return <div className="panel"><div className="toolbar"><div><h3>{title}</h3><p>Database-backed CRUD management.</p></div>{fields.length>0&&<button onClick={()=>setEdit(empty)}>+ Add</button>}</div>{fields.length===0?<MediaTable data={data} load={load}/>:<><table><thead><tr>{fields.slice(0,5).map(f=><th key={f}>{f}</th>)}<th>Actions</th></tr></thead><tbody>{data.map(x=><tr key={x.id}>{fields.slice(0,5).map(f=><td key={f}>{String(x[f]??'').slice(0,80)}</td>)}<td><button className="small" onClick={()=>setEdit(x)}>Edit</button> <button className="small danger" onClick={()=>remove(x.id)}>Delete</button></td></tr>)}</tbody></table></>}{edit&&<RecordEdit type={type} record={edit} fields={fields} close={()=>{setEdit(null);load()}}/>}</div>}
function RecordEdit({type,record,fields,close}){const[r,setR]=useState({...record});const save=async()=>{try{const d={...r};for(const k of ['publishDate'])if(d[k]==='')d[k]=null;const res=record.id?await mutate('put','/admin/'+type+'/'+record.id,d):await mutate('post','/admin/'+type,d);close()}catch(e){alert(e.response?.data?.error||'Save failed')}};return <div className="modal"><div className="modal-card wide"><h3>{record.id?'Edit':'Create'} {type}</h3>{fields.map(f=><label key={f}>{f}{f==='status'?<select value={r[f]||'DRAFT'} onChange={e=>setR({...r,[f]:e.target.value})}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select>:<input value={r[f]??''} onChange={e=>setR({...r,[f]:f==='sortOrder'?Number(e.target.value):e.target.value})}/>}</label>)}<div className="actions"><button onClick={save}>Save</button><button className="ghost" onClick={close}>Cancel</button></div></div></div>}
function MediaTable({data,load}){const[file,setFile]=useState(null),[title,setTitle]=useState('');async function upload(){if(!file)return;const c=await csrf();const fd=new FormData();fd.append('file',file);fd.append('title',title);await api.post('/admin/media/upload',fd,{headers:{'x-csrf-token':c}});setFile(null);setTitle('');load()}return <><div className="upload"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Media title"/><input type="file" onChange={e=>setFile(e.target.files[0])}/><button onClick={upload}>Upload</button></div><div className="media-grid">{data.map(m=><div className="media" key={m.id}>{m.type==='IMAGE'?<img src={ORIGIN+m.storagePath}/>:<div className="file">{m.type}</div>}<b>{m.title}</b><small>{m.category||'Uncategorised'}</small></div>)}</div></>}
function Audit(){const[data,setData]=useState([]);useEffect(()=>{api.get('/admin/audit').then(r=>setData(r.data))},[]);return <div className="panel"><h3>Audit Log</h3><table><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Entity</th><th>IP</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{new Date(x.createdAt).toLocaleString()}</td><td>{x.user?.email||'—'}</td><td>{x.action}</td><td>{x.entityType} {x.entityId||''}</td><td>{x.ip||'—'}</td></tr>)}</tbody></table></div>}
function PublicPage(){
  const {slug}=useParams();

  return (
    <iframe
      className="public-frame"
      title={`Public Page - ${slug}`}
      src={`/public-site/${slug}`}
      style={{
        width:'100%',
        height:'100vh',
        border:'0',
        display:'block'
      }}
    />
  );
}
function Root(){
  const loc=useLocation();

  useEffect(()=>{
    if(loc.pathname.startsWith('/site/')){
      const slug=loc.pathname.replace('/site/','') || 'home';
      window.location.replace(`/public-site/${slug}`);
    }
  },[loc.pathname]);

  if(loc.pathname.startsWith('/site/')){
    return <div className="public-loading">Loading public website…</div>;
  }

  return <App/>;
}
createRoot(document.getElementById('root')).render(<BrowserRouter><Root/></BrowserRouter>);